// Reading v2 — 80 original items over ten passages (pool for 50 administered).
// Skills: main_idea 10, inference 14, vocabulary_in_context 14, author_purpose_tone 12, text_structure 10,
// detail_evidence 10, rhetorical_analysis 10. Difficulty pool 16 / 36 / 28. Four choices (A–D); keys are
// rebalanced at assembly. v1 (bank-reading.ts) is untouched.
import type { BankQuestion } from "./bank-types.ts";
import { R2_P1, R2_P2, R2_P3, R2_P4, R2_P5, R2_P6, R2_P7, R2_P8, R2_P9, R2_P10, type ReadingPassage } from "./bank-reading-v2-passages.ts";
export { READING_V2_PASSAGES } from "./bank-reading-v2-passages.ts";

let n = 0;
const r = (difficulty: 1 | 2 | 3, skill: string, p: ReadingPassage, stem: string, opts: [string, string, string, string], correct: "A" | "B" | "C" | "D", rationale: string): BankQuestion => ({
  code: `RD2-${String(++n).padStart(2, "0")}`, section_key: "reading", skill, difficulty, stem,
  passage_id: p.id, passage_title: p.title, passage_text: p.text,
  choices: [{ key: "A", text: opts[0] }, { key: "B", text: opts[1] }, { key: "C", text: opts[2] }, { key: "D", text: opts[3] }],
  correct_key: correct, rationale,
});

export const READING_V2: BankQuestion[] = [
  // ---------------- P1 The Orchard Ledger (lit) : mi1 inf2 voc2 apt1 ts1 de1 ----------------
  r(1, "detail_evidence", R2_P1, "What condition does the grandmother place on the sale of the orchard?",
    ["The buyer must keep the trees", "The ledger must remain with the family", "The family must be allowed to visit", "The sale must wait until after the harvest"], "B",
    "The first sentence states her single condition: the ledger stayed with the family. The other options are never mentioned."),
  r(2, "vocabulary_in_context", R2_P1, "As used in paragraph 2, \"ostensibly\" most nearly means",
    ["genuinely", "apparently", "rudely", "repeatedly"], "B",
    "\"Ostensibly out of curiosity\" signals that curiosity was the stated or apparent reason, with the hint that the real motive differed. \"Genuinely\" is the opposite of that hint."),
  r(2, "inference", R2_P1, "The narrator's remark that the buyer's company \"grew apples the way other companies grew spreadsheets\" suggests that the buyer",
    ["is dishonest about his intentions", "values measurable output over meaning", "knows little about farming", "is secretly sentimental about the orchard"], "B",
    "Comparing apple-growing to spreadsheets frames the company as data-driven and impersonal, which fits his request for \"actual yield data.\" Nothing suggests dishonesty or ignorance of farming."),
  r(2, "author_purpose_tone", R2_P1, "The narrator's attitude toward her own seventeen-year-old self is best described as",
    ["nostalgic and approving", "bitter and resentful", "wry and self-critical", "detached and indifferent"], "C",
    "She calls herself \"impatient with both of them\" and reads the ledger \"guiltily,\" a rueful, self-aware judgment rather than approval or bitterness."),
  r(3, "inference", R2_P1, "Which statement best explains why the narrator concludes that her great-grandfather \"had not been vague\"?",
    ["She discovers that each odd entry corresponds to a specific event in the family's life.", "Her mother tells her the exact yields for every year.", "The buyer admits that the ledger contains useful data.", "The entries are written in four different handwritings."], "A",
    "Paragraph 4 gives two examples—the 1954 property dispute and births marked \"enough\"—showing the entries were precise records of meaning. The mother confirms only one event; the buyer never changes his view."),
  r(3, "vocabulary_in_context", R2_P1, "In the final paragraph, the grandmother is described as too \"scrupulous\" to mention an examination. In this context \"scrupulous\" most nearly means",
    ["careless", "conscientious", "fearful", "proud"], "B",
    "She is principled and careful—too honest to reveal that she was testing the narrator. \"Fearful\" and \"proud\" do not match a person acting on conscience."),
  r(2, "text_structure", R2_P1, "The final paragraph functions mainly to",
    ["resolve the tension by showing the grandmother accepting the narrator as a keeper of the ledger", "explain how the sale was ultimately canceled", "reveal that the buyer has changed his mind", "introduce a new conflict between mother and daughter"], "A",
    "The grandmother's quiet question, nod, and page-by-page explanation close the story by passing the ledger's meaning to the narrator. The sale is not canceled and the buyer does not reappear."),
  r(1, "main_idea", R2_P1, "Which sentence best expresses the central idea of the passage?",
    ["Selling family land is always a mistake.", "Records of what matters can be more valuable than records of what was produced.", "Young people are too impatient to appreciate history.", "Farming companies cannot understand small orchards."], "B",
    "The narrator's realization—\"The trees were the means. The ledger was the harvest.\"—captures the passage's point about meaning versus output. The other options overstate or misread details."),

  // ---------------- P2 The Fourth Leg (lit) : mi1 inf2 voc1 apt1 ts1 de1 ra1 ----------------
  r(1, "detail_evidence", R2_P2, "According to the passage, what specific part of the relay gives Devi the most trouble?",
    ["Running the curve", "The start from the blocks", "The baton exchange in the passing zone", "Maintaining speed over the final meters"], "C",
    "Paragraph 4 opens \"The exchange was the problem\" and describes the eleven-meter passing zone. The other options are not identified as difficulties."),
  r(2, "inference", R2_P2, "Marisol's \"careful blankness\" most likely reflects that she",
    ["has been told she is injured", "is choosing how to respond to losing the anchor leg", "did not expect to run at all", "is angry at Devi personally"], "B",
    "The text glosses the expression as \"the face of someone deciding what to feel,\" and Marisol had anchored for two seasons. Nothing indicates injury or personal anger."),
  r(2, "vocabulary_in_context", R2_P2, "Devi thinks Marisol's explanation might be \"a diagnosis\" rather than \"generosity.\" As used here, \"diagnosis\" most nearly means",
    ["a medical opinion", "a blunt identification of a weakness", "a formal complaint", "a prediction of victory"], "B",
    "Devi worries that Marisol is naming her flaw—poor exchanges—rather than being kind. The medical sense is figurative, and no complaint or prediction is involved."),
  r(2, "author_purpose_tone", R2_P2, "The author most likely includes Coach Ferreira's line \"Looking back is a way of running the other person's leg\" in order to",
    ["show that the coach is unreasonable", "state the passage's central lesson in the coach's voice", "explain the rules of relay racing", "foreshadow that Devi will drop the baton"], "B",
    "The line crystallizes the story's theme of trust and focusing on one's own task, which Devi then enacts by not turning. It is not rule-explanation or foreshadowing of failure."),
  r(3, "rhetorical_analysis", R2_P2, "The author's description of the baton striking Devi's palm \"with a slap that stung all the way to the elbow\" chiefly serves to",
    ["suggest that the exchange was performed incorrectly", "convey the physical relief of a successful blind exchange after a moment of fear", "criticize the third runner for passing too hard", "shift the narrative into Marisol's point of view"], "B",
    "Following \"one terrible stride her hand closed on nothing,\" the sharp sensation marks the moment of success and release. The exchange is not described as faulty."),
  r(3, "inference", R2_P2, "The final paragraph implies that Marisol",
    ["resented being replaced and did not watch", "had genuinely invested in Devi's success", "was counting the seconds until the team lost", "expected Devi to fail the exchange"], "B",
    "Marisol is on her feet before the exchange, silently counting Devi's steps as she had taught her—evidence of real investment rather than resentment or expectation of failure."),
  r(2, "text_structure", R2_P2, "How does the passage's structure build toward its climax?",
    ["It alternates between Devi's and Marisol's perspectives.", "It establishes the problem, presents advice, then shows the advice tested in a single decisive moment.", "It begins with the race and flashes back to practice.", "It lists the reasons Devi was chosen before describing the meet."], "B",
    "The passage moves from the posting and Devi's doubts, through the exchange problem and Ferreira's advice, to the race where the advice is enacted. There is no flashback structure or true alternating point of view."),
  r(1, "main_idea", R2_P2, "Which statement best expresses a theme of the passage?",
    ["Speed is the only quality that matters in a relay.", "Trusting others requires resisting the urge to control what you cannot see.", "Coaches should announce lineups well in advance.", "Rivals can never become allies."], "B",
    "Devi succeeds only when she stops looking back and trusts her teammate to arrive; Marisol's support reinforces the theme. The passage explicitly says it is \"not about who's fastest.\""),

  // ---------------- P3 The Clockmaker's Apprentice (lit) : mi1 inf2 voc2 apt1 ts1 ra1 ----------------
  r(1, "main_idea", R2_P3, "The passage as a whole is mainly about",
    ["the technical steps of repairing a mantel clock", "an apprentice learning that careful observation must come before confident action", "a conflict between an old craftsman and a modern manual", "the reasons a clock gains time in warm weather"], "B",
    "Tomas moves from manual-based certainty to patient watching, and only then is he invited to \"begin.\" Technical details serve that arc rather than being the point."),
  r(2, "vocabulary_in_context", R2_P3, "As used in paragraph 5, \"tenuous\" most nearly means",
    ["flimsy", "stubborn", "detailed", "renewed"], "A",
    "His certainty \"thinned into something more tenuous\"—weak and insubstantial. \"Stubborn\" and \"renewed\" contradict the idea of thinning."),
  r(2, "inference", R2_P3, "Tomas's repeated adjustments in paragraph 3 most strongly suggest that he",
    ["is deliberately sabotaging the clock", "is applying textbook fixes without understanding the specific cause", "has never read a repair manual", "wants to impress the clock's owner"], "B",
    "He does what \"the manuals prescribed\" and gets marginal results each time, showing procedure without diagnosis. The passage says he had read the manuals, so C is wrong."),
  r(2, "author_purpose_tone", R2_P3, "The author's tone toward Mr. Adeyemi's teaching method is best described as",
    ["mocking", "ultimately respectful", "indifferent", "openly hostile"], "B",
    "Although the method is first shown as \"maddening\" from Tomas's view, the ending validates it, and the details (\"greeting each gear,\" \"like a doctor listening\") are admiring."),
  r(3, "inference", R2_P3, "Which detail from Tomas's list most likely points toward the actual cause of the clock's error?",
    ["The mainspring being tired", "The replaced suspension spring being slightly thicker than the original", "The owner's complaint of eleven minutes", "The clock being a mantel clock"], "B",
    "A thicker suspension spring changes the pendulum's behavior and would interact with warming, fitting the afternoon gain; the mainspring was already replaced without effect. The other details are not causes."),
  r(3, "rhetorical_analysis", R2_P3, "What is the effect of ending the passage with Mr. Adeyemi pulling up \"a second stool\"?",
    ["It signals that Tomas will be dismissed from the shop.", "It shows the shift from observer and master to two collaborators, marking the real start of the apprenticeship.", "It suggests the clock has finally been repaired.", "It reveals that the old man is too tired to stand."], "B",
    "The stool is a physical symbol of partnership, reinforced by \"Now we can begin.\" The clock is explicitly not yet fixed."),
  r(2, "text_structure", R2_P3, "The passage is organized primarily",
    ["as a comparison of two repair philosophies presented side by side", "chronologically, tracing a change in the apprentice over several weeks", "as a series of unrelated anecdotes about clocks", "from the clockmaker's point of view"], "B",
    "Time markers—\"first month,\" \"second month,\" \"third week\"—structure the narrative around Tomas's development. It stays in Tomas's perspective."),
  r(1, "vocabulary_in_context", R2_P3, "In paragraph 2, decisions Tomas \"considered self-evident\" are decisions he thought were",
    ["obvious", "dangerous", "unnecessary", "expensive"], "A",
    "\"Self-evident\" means requiring no proof or explanation—obvious. This matches his impatience with the old man's pauses."),

  // ---------------- P4 The Bridge at Harrow Ford (hist) : mi1 inf1 voc1 apt1 ts1 de2 ra1 ----------------
  r(1, "detail_evidence", R2_P4, "According to the passage, what feature of Vance's design eliminated a recurring winter problem?",
    ["Its iron-oxide red paint", "Its single span with no mid-river pier", "Its lower cost", "Its wooden deck"], "B",
    "Paragraph 2 explains the single 140-foot span removed the pier that had trapped ice floes. The design cost more, not less."),
  r(2, "detail_evidence", R2_P4, "Which piece of evidence does the author cite to show how the council reached its decision?",
    ["Vance's engineering calculations", "The preserved minutes of the council meetings", "Interviews with descendants of the council members", "The newspaper caricature"], "B",
    "The author repeatedly refers to \"the minutes,\" preserved in the town archive, as the source for the debate and the turning point. The caricature concerns construction, not the decision."),
  r(2, "inference", R2_P4, "The author's statement that Penhallow's motive \"was not entirely civic\" implies that",
    ["Penhallow opposed the iron bridge", "Penhallow's offer was partly self-interested", "the council rejected Penhallow's loan", "Penhallow was a member of the council"], "B",
    "The next sentence spells it out: he stood to save more in flood damages than he risked. Nothing indicates he opposed the bridge or sat on the council."),
  r(2, "vocabulary_in_context", R2_P4, "As used in paragraph 2, \"audacious\" most nearly means",
    ["boldly daring", "carelessly cheap", "traditionally safe", "quietly modest"], "A",
    "The design's unprecedented single span and triple cost make it bold and risky. \"Traditionally safe\" describes the timber option instead."),
  r(3, "rhetorical_analysis", R2_P4, "The author includes Vance's one-sentence reply to the newspaper primarily to",
    ["prove the bridge was structurally unsound", "characterize Vance's composure and dry wit under pressure", "explain why construction took nineteen months", "show that the newspaper apologized"], "B",
    "Her retort—that the sag was drawn in the wrong place—reveals confidence and humor amid delays and ridicule. It does not explain the delay or indicate an apology."),
  r(3, "text_structure", R2_P4, "How does the third paragraph shift the passage's argument?",
    ["It moves the explanation for the decision from engineering and cost to a change in how the question was framed.", "It introduces the newspaper's criticism of the design.", "It describes the bridge's later use by automobiles.", "It compares Harrow Ford to other river towns."], "A",
    "The paragraph opens \"What tipped the decision... was neither engineering nor economy but a letter,\" and ends with the reframing: \"It was insurance.\" The other options belong to different paragraphs or do not occur."),
  r(2, "author_purpose_tone", R2_P4, "The author's purpose in the final paragraph is most likely to",
    ["argue that iron bridges are superior to modern ones", "emphasize the lasting vindication of Vance's design", "criticize the town for retiring the bridge", "explain modern traffic regulations"], "B",
    "Noting nearly a century of service, unplanned automobile traffic, the preserved paint color, and the never-rebuilt pier all underscore that the bold choice proved right."),
  r(1, "main_idea", R2_P4, "Which statement best summarizes the passage?",
    ["A small town chose a costly but durable bridge design after a business owner's offer reframed the expense as protection, and the choice endured for a century.", "A young engineer failed to complete a bridge on time and was mocked by the press.", "Timber bridges are cheaper than iron bridges but less attractive.", "Town councils in the nineteenth century rarely kept records of their debates."], "A",
    "This option captures the decision, its turning point, and the outcome. The others isolate details or contradict the text (the records were unusually candid)."),

  // ---------------- P5 Mapping the Unseen Coast (hist) : mi1 inf1 voc2 apt1 ts1 de1 ra1 ----------------
  r(1, "detail_evidence", R2_P5, "Why did the survey office initially refuse to publish Marrow's charts?",
    ["They contained measurement errors.", "They were considered confusing to ordinary mariners.", "They were too expensive to print in several inks.", "Marrow had not finished the survey."], "B",
    "The passage quotes the office's objection directly. His triangulation is described as accurate, so A is wrong."),
  r(2, "vocabulary_in_context", R2_P5, "As used in paragraph 3, \"prescient\" most nearly means",
    ["outdated", "showing foresight", "overly detailed", "widely copied"], "B",
    "Modern cartographers see Marrow's layered method as ahead of its time—foresighted. His colleagues' word \"eccentric\" is contrasted with this later judgment."),
  r(2, "inference", R2_P5, "The passage suggests that Marrow's predecessors' practice of \"publishing charts anyway and appending warnings\" was",
    ["more accurate than Marrow's method", "an inadequate response to a shifting coastline", "required by law", "the method eventually adopted by geologists"], "B",
    "Marrow \"refused\" this approach and the later shipwrecks on charted open water expose its inadequacy. Nothing suggests legal requirement."),
  r(2, "author_purpose_tone", R2_P5, "The author describes Marrow's reply to the survey office as notable for its \"restraint.\" This word choice conveys the author's",
    ["disapproval of Marrow's rudeness", "admiration for Marrow's calm, pointed response", "confusion about Marrow's meaning", "belief that Marrow should have argued more forcefully"], "B",
    "Calling the reply \"worth quoting for its restraint\" praises how much he conveyed while staying measured. It is not a criticism."),
  r(3, "vocabulary_in_context", R2_P5, "In paragraph 2, the statement that \"accuracy and usefulness had come apart\" most nearly means that",
    ["Marrow's measurements had become unreliable", "a precisely correct chart could still be dangerous because the coast kept changing", "sailors no longer trusted any charts", "usefulness mattered more than accuracy to the survey office"], "B",
    "The next sentence explains: a chart faithful to 1848 could wreck a ship in 1851. The measurements themselves remained accurate."),
  r(3, "rhetorical_analysis", R2_P5, "The final two sentences—\"He had set out to make a map that would remain useful. He had, almost incidentally, made a history.\"—achieve their effect primarily through",
    ["a rhetorical question", "parallel structure that contrasts intention with unexpected outcome", "an extended metaphor comparing maps to ships", "technical jargon"], "B",
    "The matched sentence frames (\"He had set out... He had... made\") set purpose against unintended legacy. No question, metaphor, or jargon is used."),
  r(2, "text_structure", R2_P5, "Which best describes the organization of the passage?",
    ["Problem, unconventional solution, resistance, and eventual vindication", "A list of Marrow's measurements in chronological order", "A comparison of several surveyors' methods", "An argument followed by counterarguments"], "A",
    "The passage moves from the shifting-coast problem to Marrow's layered charts, the office's refusal, and the charts' later value. The other structures do not fit."),
  r(1, "main_idea", R2_P5, "The central idea of the passage is that Marrow",
    ["was punished with an undesirable assignment", "created charts that honestly showed change and uncertainty, which made them useful far beyond their original purpose", "was the most accurate surveyor of his era", "invented triangulation"], "B",
    "The passage's emphasis is on his layered, dated method and its long afterlife. His accuracy and the \"exile\" are supporting details."),

  // ---------------- P6 The Ground That Remembers (info) : mi1 inf1 voc1 apt1 ts1 de2 ra1 ----------------
  r(1, "detail_evidence", R2_P6, "According to the passage, what preserves ancient organic matter in permafrost?",
    ["A special chemical reaction", "Cold that slows decomposing microbes", "The absence of oxygen underground", "Layers of ice that seal it"], "B",
    "Paragraph 1 says preservation occurs \"not by any special chemistry but by cold, which slows the microbes.\""),
  r(2, "detail_evidence", R2_P6, "What device do engineers use to keep the ground beneath northern towns frozen?",
    ["Sinkhole barriers", "Thermosiphons that remove heat in winter", "Heated pipelines", "Concrete pilings"], "B",
    "Paragraph 3 describes passive thermosiphons that draw heat out of the soil and store cold for summer. Sinkholes (thermokarst) are a symptom, not a device."),
  r(2, "vocabulary_in_context", R2_P6, "As used in paragraph 2, \"liability\" most nearly means",
    ["an advantage", "a source of risk or harm", "a legal contract", "a scientific estimate"], "B",
    "The preservation that was once neutral now creates danger as thaw releases carbon. The word contrasts with the preceding paragraph's description of preservation."),
  r(2, "inference", R2_P6, "Based on the passage, why is the release of permafrost carbon described as a \"feedback loop\"?",
    ["Because the carbon eventually returns to the ground", "Because released carbon causes warming that thaws more permafrost, releasing more carbon", "Because scientists must repeatedly re-measure the inventory", "Because methane and carbon dioxide cancel each other out"], "B",
    "The paragraph traces the cycle explicitly: release accelerates warming, which thaws more permafrost. The gases do not cancel; methane is described as more potent."),
  r(3, "text_structure", R2_P6, "The final paragraph differs from the earlier paragraphs in that it",
    ["introduces the definition of permafrost", "distinguishes what is established from what remains uncertain", "describes damage to roads and buildings", "presents a solution to the problem"], "B",
    "The last paragraph explicitly separates the well-established carbon inventory from the uncertain release rate. Definitions, damage, and thermosiphons appear earlier."),
  r(3, "rhetorical_analysis", R2_P6, "The closing sentence, \"The ground is remembering, and what it remembers is warmth,\" primarily",
    ["introduces a new scientific finding", "personifies the permafrost to unify the passage's title and its warning", "contradicts the author's earlier caution", "summarizes the engineering response"], "B",
    "The personification echoes the title and turns the technical account into a memorable warning without claiming new data. It does not contradict the caution, since the direction of change is stated as undisputed."),
  r(2, "author_purpose_tone", R2_P6, "The author's tone throughout the passage is best described as",
    ["alarmist and exaggerated", "measured and precise while still conveying seriousness", "humorous and light", "dismissive of scientific concern"], "B",
    "The author uses careful qualifiers (\"roughly,\" \"estimate,\" \"suggestive\") and distinguishes knowledge from inference, yet states the danger plainly."),
  r(1, "main_idea", R2_P6, "Which statement best expresses the main idea of the passage?",
    ["Permafrost is easy to define but has no practical importance.", "Thawing permafrost threatens both the climate and the communities built on it, though the pace of change is uncertain.", "Engineers have solved the problem of thawing ground.", "Methane is the only gas released by permafrost."], "B",
    "The passage covers the carbon feedback, infrastructure damage, and the limits of current knowledge. The others contradict specific statements."),

  // ---------------- P7 Why the Brain Rehearses at Night (info) : mi1 inf2 voc1 apt1 ts1 de1 ra1 ----------------
  r(1, "detail_evidence", R2_P7, "According to the passage, what did researchers observe in rats' hippocampal cells during sleep?",
    ["The cells stopped firing entirely.", "The cells fired in the same sequence as during the maze, but faster.", "The cells fired randomly.", "The cells moved to the cortex."], "B",
    "Paragraph 2 describes the same cells firing in the same order \"but compressed,\" which researchers call replay."),
  r(2, "vocabulary_in_context", R2_P7, "As used in paragraph 1, \"idling\" most nearly means",
    ["running without doing useful work", "sleeping deeply", "repairing damage", "speeding up"], "A",
    "\"Biological idling\" compares the sleeping brain to an engine running but not working—a view the passage says was overturned."),
  r(2, "inference", R2_P7, "The word-pair experiment described in paragraph 3 is included mainly to",
    ["prove that rats and humans have identical brains", "provide human evidence that sleep strengthens memory", "show that staying awake improves recall", "explain how the cortex differs from the hippocampus"], "B",
    "The experiment shows people who sleep recall more, linking replay in animals to human learning. It shows the opposite of C."),
  r(3, "inference", R2_P7, "Which conclusion is best supported by the passage's account of replay being selective and sometimes reversed?",
    ["Sleep faithfully records every event of the day.", "The sleeping brain actively processes and reorganizes experience rather than merely storing it.", "Reverse replay causes false memories.", "Emotional memories are always forgotten."], "B",
    "Preferential rehearsal of important experiences and recombination of fragments support active processing, which some interpret as problem-solving. The passage says replay is \"not a faithful recording.\""),
  r(3, "rhetorical_analysis", R2_P7, "The final sentence—\"she has traded the rehearsal for the reading\"—is effective primarily because it",
    ["introduces a new scientific study", "uses a concrete, relatable example and antithesis to make the abstract finding practical", "questions the reliability of the research", "repeats the passage's opening sentence"], "B",
    "The student example translates the neuroscience into a daily decision, and the balanced contrast (rehearsal vs. reading) sharpens the point."),
  r(3, "author_purpose_tone", R2_P7, "The author's phrase \"the field remains appropriately cautious\" reveals an attitude that is",
    ["skeptical of all sleep research", "respectful of scientists' restraint about unproven interpretations", "frustrated by slow progress", "certain that replay solves problems"], "B",
    "\"Appropriately\" approves of the caution about the offline problem-solving interpretation, which the author labels \"suggestive rather than conclusive.\""),
  r(3, "text_structure", R2_P7, "The passage develops its explanation of replay by",
    ["presenting evidence, then describing two functions in order of increasing surprise", "listing objections and refuting each", "comparing sleep in several animal species", "narrating one scientist's career"], "A",
    "After the neuron evidence, the author labels consolidation \"the first\" function and the selective, recombining replay \"more surprising.\""),
  r(3, "main_idea", R2_P7, "Which statement best captures the passage's central claim?",
    ["Sleep is a passive rest period that follows learning.", "During sleep the brain replays and reshapes the day's experiences, making sleep an active part of learning.", "Rats learn mazes faster than humans learn word pairs.", "Deep sleep should be avoided before exams."], "B",
    "The passage's conclusion—\"sleep is part of learning rather than a pause from it\"—rests on the replay evidence and its two functions."),

  // ---------------- P8 The Ubiquitous Stranger (info) : mi1 inf1 voc2 apt1 ts1 de1 ra1 ----------------
  r(1, "detail_evidence", R2_P8, "According to the passage, why are medieval window panes often thicker at the bottom?",
    ["Glass slowly flowed downward over centuries.", "Flat-glass techniques were imperfect and glaziers installed the heavier edge downward.", "Builders added extra glass for insulation.", "The panes were repeatedly repaired."], "B",
    "Paragraph 2 debunks the flow myth and gives the manufacturing-and-installation explanation. The calculated flow time exceeds the age of the universe."),
  r(2, "vocabulary_in_context", R2_P8, "As used in the title and first paragraph, \"ubiquitous\" most nearly means",
    ["fragile", "found everywhere", "expensive", "ancient"], "B",
    "The opening describes glass as \"so pervasive that it has become nearly invisible,\" which defines ubiquitous. \"Stranger\" refers to how poorly we understand it."),
  r(2, "vocabulary_in_context", R2_P8, "In paragraph 1, an \"amorphous\" solid is one that",
    ["has a regular crystal lattice", "lacks an ordered internal structure", "melts at low temperatures", "cannot be shaped"], "B",
    "The passage defines it: rigid, but with atoms in a \"disordered jumble.\" This is the opposite of a crystal's ordered lattice."),
  r(2, "inference", R2_P8, "The passage implies that the persistence of the \"flowing glass\" myth is due mainly to the fact that it",
    ["was published in a famous textbook", "offers a plausible-sounding explanation for something people can see", "is supported by modern calculations", "was promoted by glassmakers"], "B",
    "The author uses the myth to illustrate \"how a plausible explanation can outlive its evidence.\" Calculations actually refute it."),
  r(3, "text_structure", R2_P8, "How do paragraphs 3 and 4 relate to each other?",
    ["Paragraph 3 explains why disorder makes glass both useful and brittle; paragraph 4 shows how makers exploit that understanding to reduce brittleness.", "Paragraph 3 describes ancient glass; paragraph 4 describes modern glass.", "Paragraph 3 presents a myth; paragraph 4 debunks it.", "Paragraph 4 contradicts the claims of paragraph 3."], "A",
    "Paragraph 4 opens \"Modern glassmakers exploit this understanding,\" building directly on the strength-and-brittleness explanation. The myth is handled in paragraph 2."),
  r(3, "rhetorical_analysis", R2_P8, "The concluding claim that \"much of engineering consists of being reliably right about things we cannot yet fully explain\" functions to",
    ["undermine confidence in glass products", "generalize the passage's specific case into a broader observation about applied knowledge", "introduce the topic of tempered glass", "argue that scientists should stop studying glass"], "B",
    "The sentence widens the lesson from glass to engineering as a whole, framing practical mastery without complete theory as normal rather than troubling."),
  r(2, "author_purpose_tone", R2_P8, "The author's tone in discussing the century-long scientific argument about glass is best described as",
    ["frustrated", "amused and candid", "dismissive", "anxious"], "B",
    "Phrases like \"the honest answer is that scientists have argued about it for a century\" and \"the ubiquitous stranger\" treat the uncertainty with good humor and openness."),
  r(3, "main_idea", R2_P8, "Which statement best expresses the central idea of the passage?",
    ["Glass is a liquid that flows extremely slowly.", "Glass's disordered structure explains both its usefulness and its brittleness, and engineers have learned to exploit it despite lingering questions about its nature.", "Phone screens are made of tempered glass.", "Medieval glaziers were careless craftsmen."], "B",
    "This option integrates the definition, the myth, the strength/brittleness trade-off, and the modern techniques. A restates the myth; C confuses tempered with chemically strengthened glass."),

  // ---------------- P9 The Case Against the Late Bell (arg) : mi1 inf1 voc1 apt2 ts1 ra2 ----------------
  r(1, "main_idea", R2_P9, "What is the author's central claim?",
    ["High schools should start later because adolescent biology makes early starts harmful and the logistical objections are solvable.", "Students should be taught better sleep discipline.", "Bus schedules are the most important factor in school planning.", "Teen driving should be restricted."], "A",
    "The thesis is stated early (\"The evidence is settled\") and restated in the closing imperative, \"Move the bell. Solve the buses.\""),
  r(2, "vocabulary_in_context", R2_P9, "As used in paragraph 2, \"disinclined\" most nearly means",
    ["unable due to habit", "naturally unwilling or unsuited", "eager", "forbidden"], "B",
    "The author contrasts being \"reluctant\" with being \"biologically disinclined\"—not merely unwilling by choice but unsuited by nature."),
  r(2, "author_purpose_tone", R2_P9, "The author's attitude toward opponents who \"change the subject to logistics\" is best described as",
    ["sympathetic but firm", "openly contemptuous", "uncertain", "indifferent"], "A",
    "The author concedes \"These are real difficulties\" before insisting other districts have solved them—acknowledging the concern while refusing to accept it as decisive."),
  r(3, "rhetorical_analysis", R2_P9, "The comparison of circadian rhythm to height in paragraph 2 is intended to",
    ["show that taller students need more sleep", "emphasize that sleep timing is a fixed biological trait, not a behavior to be corrected", "suggest that students exaggerate their tiredness", "introduce statistical evidence"], "B",
    "The analogy argues one cannot be \"disciplined into\" a different rhythm any more than a different height, countering the discipline framing."),
  r(3, "rhetorical_analysis", R2_P9, "How does the author handle the objection that a later start would \"coddle\" students?",
    ["By ignoring it", "By reframing the schedule as an environmental defect comparable to poor lighting or heating", "By citing accident statistics", "By admitting it is partly valid"], "B",
    "Paragraph 4 calls the argument a mistake that treats biology as character, then compares the schedule to classroom defects \"we fix.\" Statistics appear in paragraph 3, not here."),
  r(3, "inference", R2_P9, "The author's remark that the coddling objection is \"made least often aloud\" implies that",
    ["few people actually hold this view", "the author believes it quietly motivates much opposition even though it is rarely stated", "school boards have formally rejected it", "the objection is the strongest one"], "B",
    "Calling it \"the most revealing objection\" while noting it is seldom voiced suggests an unspoken but influential attitude."),
  r(2, "text_structure", R2_P9, "Which best describes the overall structure of the argument?",
    ["Claim, biological explanation, evidence of results, rebuttal of objections, call to action", "A personal narrative followed by a moral", "A list of school districts and their schedules", "A neutral comparison of early and late start times"], "A",
    "Paragraphs move in exactly that order, ending with the imperative \"Move the bell.\" The piece is explicitly persuasive, not neutral."),
  r(3, "author_purpose_tone", R2_P9, "The final paragraph's short, direct sentences are intended to convey",
    ["hesitation about the proposal", "decisive confidence that the solution is simple to state even if work is required", "sarcasm toward students", "a change of topic"], "B",
    "\"Move the bell. Solve the buses.\" delivers the conclusion as plain commands, projecting certainty after the detailed argument."),

  // ---------------- P10 Two Views of the Public Library (paired) : mi1 inf1 voc1 apt2 ts1 de1 ra1 ----------------
  r(1, "detail_evidence", R2_P10, "According to Text 1, how has library use changed over the past decade?",
    ["Both physical and digital lending have declined.", "Physical circulation has fallen while digital lending has more than tripled.", "Digital lending has fallen while physical circulation has grown.", "Use has remained constant."], "B",
    "Text 1 gives the figures: physical circulation down 38 percent, digital lending more than tripled."),
  r(2, "vocabulary_in_context", R2_P10, "In Text 2, the librarian says \"I do not doubt its arithmetic. I doubt its accounting.\" In this context, \"accounting\" most nearly refers to",
    ["the memo's addition errors", "what the memo chooses to count as library use", "the city's tax records", "the cost of the building"], "B",
    "The librarian accepts the numbers but argues that circulation ignores people who use the library without borrowing—an objection to what is counted, not to the math."),
  r(2, "author_purpose_tone", R2_P10, "The tone of Text 1 is best described as",
    ["angry and dismissive", "businesslike and detached", "sentimental", "playful"], "B",
    "Text 1 relies on square footage, percentages, and projected savings, and states \"sentiment is not a line item.\" It is neither hostile nor emotional."),
  r(3, "rhetorical_analysis", R2_P10, "The librarian's list of the newspaper reader, the students, and the woman filing for benefits serves primarily to",
    ["prove that circulation statistics are inaccurate", "supply concrete counterexamples to the memo's measure of value", "argue that the library should lend more books", "describe the librarian's daily schedule"], "B",
    "Each example is someone who \"used the library\" without borrowing, directly challenging circulation as the measure. The statistics themselves are not disputed."),
  r(3, "inference", R2_P10, "Which statement would the author of Text 1 most likely make in response to Text 2?",
    ["The people described could be served by the neighborhood branches and extended hours the savings would fund.", "Digital lending should be discontinued.", "The Central building should be demolished immediately.", "Circulation statistics should be ignored."], "A",
    "Text 1 proposes redirecting savings into extended branch hours and a bookmobile, which is the natural reply to the claim that the library is a needed place. Text 1 explicitly rejects demolition."),
  r(3, "author_purpose_tone", R2_P10, "The librarian's description of the preserved reading room as \"a beautiful room... in a building full of apartments no one who uses that room could afford\" conveys",
    ["gratitude for the preservation plan", "irony about preserving a space while displacing the people it serves", "confusion about the redevelopment", "support for mixed-use development"], "B",
    "The sentence contrasts the room's preservation with the exclusion of its users, undercutting the memo's claim that the landmark would be saved."),
  r(2, "text_structure", R2_P10, "How does Text 2 respond to the structure of Text 1?",
    ["It presents its own budget figures to challenge the memo's arithmetic.", "It accepts the memo's data but redefines the central question from efficiency to what a library is for.", "It ignores the memo entirely.", "It proposes a larger downtown library."], "B",
    "Text 2 concedes the numbers and closes by reframing: \"consider what a 'landmark' is for.\" It offers no competing figures."),
  r(3, "main_idea", R2_P10, "Taken together, the two texts primarily present a disagreement about",
    ["whether the city can afford any libraries", "how the value of a public library should be measured", "whether digital books are better than printed ones", "the architecture of the Central building"], "B",
    "Text 1 measures value by efficiency and circulation; Text 2 by the people and place the data omit. Neither questions whether libraries should exist."),
];
