// Written Expression — 50 original items.
// Quotas: grammar_usage 14, punctuation_capitalization 12, sentence_structure 12, organization 12.
import type { BankQuestion } from "./bank-types.ts";

const g = (
  code: string, difficulty: 1 | 2 | 3, skill: string, stem: string,
  opts: [string, string, string, string], correct: string, rationale: string,
): BankQuestion => ({
  code, section_key: "written_expression", skill, difficulty, stem,
  choices: [{ key: "A", text: opts[0] }, { key: "B", text: opts[1] }, { key: "C", text: opts[2] }, { key: "D", text: opts[3] }],
  correct_key: correct, rationale,
});

export const WRITTEN: BankQuestion[] = [
  // ===== grammar_usage (14) =====
  g("WE-01", 1, "grammar_usage", "Choose the sentence that is written correctly.",
    ["Neither of the twins have finished their project.", "Neither of the twins has finished the project.", "Neither of the twins are finishing the project.", "Neither of the twins were finished the project."],
    "B", "'Neither' is singular and takes the singular verb 'has.'"),
  g("WE-02", 2, "grammar_usage", "Choose the word that correctly completes the sentence.\n\nThe coach gave the trophy to Marcus and ____ after the final match.",
    ["I", "me", "myself", "mine"], "B", "The pronoun is the object of the preposition 'to,' so the object form 'me' is correct."),
  g("WE-03", 2, "grammar_usage", "Which sentence uses verb tense consistently?",
    ["Kira opened the notebook and finds her old drawings.", "Kira opens the notebook and found her old drawings.", "Kira opened the notebook and found her old drawings.", "Kira opening the notebook and finding her old drawings."],
    "C", "Both verbs are in the past tense, so the sentence is consistent."),
  g("WE-04", 2, "grammar_usage", "Choose the correct word.\n\nThe committee reviewed ____ own bylaws before voting.",
    ["it's", "its", "its'", "their's"], "B", "'Its' is the possessive form; 'it's' means 'it is.'"),
  g("WE-05", 1, "grammar_usage", "Which sentence uses the correct verb form?",
    ["The team have won every home game.", "The team has won every home game.", "The team having won every home game.", "The team were won every home game."],
    "B", "'Team' acts as a single unit here and takes the singular verb 'has.'"),
  g("WE-06", 3, "grammar_usage", "Which sentence uses the comparison correctly?",
    ["Of the two routes, the coastal one is the most scenic.", "Of the two routes, the coastal one is more scenic.", "Of the two routes, the coastal one is scenicest.", "Of the two routes, the coastal one is more scenicer."],
    "B", "With two items, use the comparative 'more scenic,' not the superlative."),
  g("WE-07", 2, "grammar_usage", "Choose the correct word.\n\nThe new rules will ____ students more time between classes.",
    ["affect", "effect", "affects", "effected"], "A", "'Affect' is the verb meaning to influence; 'effect' is normally the noun."),
  g("WE-08", 3, "grammar_usage", "Which sentence is correct?",
    ["Each of the volunteers brought their own tools.", "Each of the volunteers brought his or her own tools.", "Each of the volunteers bring their own tools.", "Each of the volunteers have brought tools."],
    "B", "'Each' is singular, so both the verb and the pronoun must be singular."),
  g("WE-09", 2, "grammar_usage", "Choose the correct word pair.\n\nThere are ____ chairs in the room than we need, so we should move ____ of them.",
    ["fewer, some", "less, some", "fewer, much", "less, much"], "A", "Use 'fewer' with countable nouns like chairs, and 'some' with a countable quantity."),
  g("WE-10", 1, "grammar_usage", "Which sentence uses the pronoun correctly?",
    ["Him and I studied together.", "He and me studied together.", "He and I studied together.", "Me and him studied together."],
    "C", "Both pronouns are subjects, so the subject forms 'he' and 'I' are required."),
  g("WE-11", 3, "grammar_usage", "Which sentence uses the verb correctly?",
    ["If I was the captain, I would change the warm-up.", "If I were the captain, I would change the warm-up.", "If I am the captain, I would change the warm-up.", "If I be the captain, I would change the warm-up."],
    "B", "A hypothetical condition takes the subjunctive 'were.'"),
  g("WE-12", 2, "grammar_usage", "Choose the correct word.\n\nAfter the rehearsal, the singers had ____ their scripts on the stage.",
    ["lay", "laid", "lain", "lied"], "B", "'Laid' is the past participle of 'lay' (to place something)."),
  g("WE-13", 2, "grammar_usage", "Which sentence is written correctly?",
    ["The package was sent to Elena and I.", "The package was sent to Elena and myself.", "The package was sent to Elena and me.", "The package was sent to I and Elena."],
    "C", "The pronoun follows the preposition 'to,' so the object form 'me' is used."),
  g("WE-14", 3, "grammar_usage", "Which sentence avoids a double negative?",
    ["We didn't see nothing unusual at the site.", "We didn't see anything unusual at the site.", "We never saw nothing unusual at the site.", "We hadn't seen nothing unusual at the site."],
    "B", "Only B pairs a single negative with 'anything.'"),

  // ===== punctuation_capitalization (12) =====
  g("WE-15", 2, "punctuation_capitalization", "Which sentence uses commas correctly?",
    ["After the storm passed, we walked to the harbor, and counted the boats.", "After the storm passed we walked to the harbor and counted the boats.", "After the storm passed, we walked to the harbor and counted the boats.", "After, the storm passed we walked to the harbor and, counted the boats."],
    "C", "A comma follows the introductory clause; no comma is needed before 'and' joining two verbs."),
  g("WE-16", 1, "punctuation_capitalization", "Which sentence is capitalized correctly?",
    ["Last Summer we visited aunt Rosa in Chicago.", "Last summer we visited Aunt Rosa in Chicago.", "Last summer we visited aunt Rosa in chicago.", "last Summer we visited Aunt rosa in Chicago."],
    "B", "Seasons are lowercase; 'Aunt Rosa' is a title used with a name; city names are capitalized."),
  g("WE-17", 2, "punctuation_capitalization", "Which sentence uses the apostrophe correctly?",
    ["The students' lockers were repainted over the break.", "The student's lockers were repainted over the break, all forty of them.", "The students lockers' were repainted over the break.", "The studentes' lockers were repainted over the break."],
    "A", "The plural possessive of 'students' places the apostrophe after the s."),
  g("WE-18", 2, "punctuation_capitalization", "Which sentence uses quotation marks and punctuation correctly?",
    ['"Bring your field notes", said Ms. Duran.', '"Bring your field notes," said Ms. Duran.', '"Bring your field notes." said Ms. Duran.', '"Bring your field notes" said Ms. Duran.'],
    "B", "The comma belongs inside the closing quotation mark before the speech tag."),
  g("WE-19", 3, "punctuation_capitalization", "Which sentence uses the semicolon correctly?",
    ["The ferry was delayed; we waited on the pier.", "The ferry was delayed; and we waited on the pier.", "The ferry was delayed; because of the fog.", "The ferry was delayed, we waited on the pier."],
    "A", "A semicolon joins two independent clauses without a conjunction."),
  g("WE-20", 2, "punctuation_capitalization", "Which sentence is punctuated correctly?",
    ["We packed three things water, maps, and batteries.", "We packed three things: water, maps, and batteries.", "We packed three things; water, maps, and batteries.", "We packed: three things water, maps and batteries."],
    "B", "A colon after a complete clause introduces the list."),
  g("WE-21", 1, "punctuation_capitalization", "Which sentence is capitalized correctly?",
    ["My favorite subject is History, and I also like spanish.", "My favorite subject is history, and I also like Spanish.", "My Favorite subject is history, and I also like spanish.", "My favorite subject is History, and I also like Spanish."],
    "B", "General subjects are lowercase, but languages are always capitalized."),
  g("WE-22", 3, "punctuation_capitalization", "Which sentence uses commas correctly with a nonessential phrase?",
    ["My cousin who lives in Denver, is visiting in April.", "My cousin, who lives in Denver is visiting in April.", "My cousin, who lives in Denver, is visiting in April.", "My cousin who lives in Denver is visiting, in April."],
    "C", "A nonessential clause is set off by commas on both sides."),
  g("WE-23", 2, "punctuation_capitalization", "Which sentence uses the hyphen correctly?",
    ["She gave a well-prepared presentation.", "She gave a well prepared-presentation.", "She gave a wellprepared presentation.", "She gave a well-prepared-presentation."],
    "A", "A compound adjective before a noun is hyphenated."),
  g("WE-24", 2, "punctuation_capitalization", "Which sentence is punctuated correctly?",
    ["Dr. Aziz our new principal will speak at the assembly.", "Dr. Aziz, our new principal, will speak at the assembly.", "Dr. Aziz, our new principal will speak at the assembly.", "Dr. Aziz our new principal, will speak at the assembly."],
    "B", "The appositive 'our new principal' is set off by a pair of commas."),
  g("WE-25", 3, "punctuation_capitalization", "Which sentence correctly punctuates the title?",
    ['We read the poem The Long Bridge in class today.', 'We read the poem "The Long Bridge" in class today.', 'We read the poem \'the long bridge\' in class today.', 'We read the poem "the Long bridge" in class today.'],
    "B", "Short works such as poems take quotation marks, and the major words are capitalized."),
  g("WE-26", 1, "punctuation_capitalization", "Which sentence ends with correct punctuation?",
    ["Could you tell me where the library is.", "Could you tell me where the library is?", "Could you tell me where the library is!", "Could you tell me where the library is,"],
    "B", "The sentence asks a direct question, so it ends with a question mark."),

  // ===== sentence_structure (12) =====
  g("WE-27", 2, "sentence_structure", "Which of the following is a complete sentence?",
    ["Because the museum closed early on Sundays.", "Running through the empty gallery before closing.", "The guard, who had worked there for years, locked the doors.", "Although the paintings were covered for cleaning."],
    "C", "Only C has an independent clause with a subject ('the guard') and a main verb ('locked')."),
  g("WE-28", 3, "sentence_structure", "Which revision best combines the two sentences?\n\nThe bridge was built in 1932. It is still the longest in the county.",
    ["The bridge was built in 1932, it is still the longest in the county.", "Built in 1932, the bridge is still the longest in the county.", "The bridge was built in 1932 and still the longest in the county it is.", "The bridge, built in 1932 and still the longest in the county."],
    "B", "B is clear and complete; A is a comma splice, C is awkward, and D is a fragment."),
  g("WE-29", 2, "sentence_structure", "Which sentence corrects the run-on?\n\nThe rain stopped we finished the game.",
    ["The rain stopped, we finished the game.", "The rain stopped we finished, the game.", "After the rain stopped, we finished the game.", "The rain stopped finished the game."],
    "C", "Adding the subordinating word 'after' joins the clauses correctly."),
  g("WE-30", 3, "sentence_structure", "Which sentence corrects the misplaced modifier?\n\nWalking to the bus stop, the rain soaked my jacket.",
    ["Walking to the bus stop, my jacket was soaked by the rain.", "The rain, walking to the bus stop, soaked my jacket.", "Walking to the bus stop, I got my jacket soaked by the rain.", "My jacket was soaked walking the rain to the bus stop."],
    "C", "The person, not the rain or the jacket, is doing the walking."),
  g("WE-31", 2, "sentence_structure", "Which sentence uses parallel structure?",
    ["She likes hiking, swimming, and to bike.", "She likes to hike, swimming, and biking.", "She likes hiking, swimming, and biking.", "She likes hike, swim, and biking."],
    "C", "All three items use the same -ing form."),
  g("WE-32", 1, "sentence_structure", "Which group of words is a fragment?",
    ["The lights flickered twice.", "Which surprised everyone in the room.", "We waited in the hallway.", "Nobody moved."],
    "B", "B is a dependent clause with no independent clause to complete it."),
  g("WE-33", 3, "sentence_structure", "Which revision is most concise without losing meaning?\n\nDue to the fact that the delivery was late, we had to postpone the opening of the store.",
    ["Due to the fact of the late delivery, we postponed the store opening.", "Because the delivery was late, we postponed the store opening.", "The delivery being late, so we had to postpone the opening of the store.", "We postponed, due to the fact that the delivery was late, the opening."],
    "B", "'Because' replaces the wordy phrase and the sentence stays clear."),
  g("WE-34", 2, "sentence_structure", "Which sentence best combines the ideas?\n\nThe experiment failed twice. The team learned what to change.",
    ["The experiment failed twice, the team learned what to change.", "Although the experiment failed twice, the team learned what to change.", "The experiment failed twice the team learned what to change.", "The experiment failed twice, and learning what to change."],
    "B", "The subordinating conjunction shows the relationship and avoids a splice."),
  g("WE-35", 2, "sentence_structure", "Which sentence corrects the faulty comparison?\n\nOur gym is larger than the school across town.",
    ["Our gym is larger than across town.", "Our gym is larger than the gym at the school across town.", "Our gym is more larger than the school across town.", "Our gym, larger than the school across town."],
    "B", "The comparison must be between two gyms, not a gym and a school."),
  g("WE-36", 1, "sentence_structure", "Which sentence is a correctly joined compound sentence?",
    ["The bell rang, the students stayed seated.", "The bell rang, but the students stayed seated.", "The bell rang but, the students stayed seated.", "The bell rang but the students, stayed seated."],
    "B", "A comma plus the coordinating conjunction 'but' joins two independent clauses."),
  g("WE-37", 3, "sentence_structure", "Which revision removes the shift in point of view?\n\nWhen a student studies regularly, you remember more on test day.",
    ["When a student studies regularly, they remembers more on test day.", "When students study regularly, they remember more on test day.", "When a student studies regularly, you remembers more on test day.", "When you study regularly, a student remembers more on test day."],
    "B", "B keeps the same plural third-person subject throughout."),
  g("WE-38", 2, "sentence_structure", "Which sentence is written most clearly?",
    ["The report that was written by the committee that met on Tuesday was long.", "The report, written by Tuesday's committee, was long.", "The report was long that the committee wrote on Tuesday.", "Written the report by the committee Tuesday, it was long."],
    "B", "B states the same information without stacked relative clauses."),

  // ===== organization (12) =====
  g("WE-39", 3, "organization", "Read the paragraph. Which sentence does NOT belong?\n\n(1) Community gardens turn empty lots into useful green space. (2) Neighbors grow vegetables, share tools, and get to know one another. (3) My cousin once grew a pumpkin that weighed sixty pounds. (4) Studies show that streets near community gardens report less litter and more foot traffic.",
    ["Sentence 1", "Sentence 2", "Sentence 3", "Sentence 4"],
    "C", "Sentence 3 is a personal anecdote that does not support the paragraph's point about community benefits."),
  g("WE-40", 2, "organization", "Which sentence would be the best topic sentence for a paragraph about the benefits of walking to school?",
    ["Some students live very far from school.", "Walking to school offers students exercise, fresh air, and time to think.", "Buses arrive at 7:45 each morning.", "Sneakers come in many colors."],
    "B", "B states the main point and previews the supporting details."),
  g("WE-41", 2, "organization", "Which transition best fits the blank?\n\nThe first trial produced no usable data. ____, the team redesigned the sensor before trying again.",
    ["However", "Therefore", "Nevertheless", "For example"],
    "B", "The second sentence states a result, so a cause-and-effect transition fits."),
  g("WE-42", 2, "organization", "Which transition best fits the blank?\n\nThe coastal route is longer. ____, it avoids the construction on the highway.",
    ["However", "Similarly", "In addition", "Finally"],
    "A", "The two clauses contrast, so a contrast transition is needed."),
  g("WE-43", 3, "organization", "Where should the following sentence be added?\n\n\"Volunteers must complete a two-hour safety course before their first shift.\"\n\n(1) The shelter relies on more than sixty volunteers. (2) They walk dogs, clean kennels, and greet visitors. (3) Training is taken seriously. (4) Most volunteers stay for more than a year.",
    ["Before sentence 1", "After sentence 1", "After sentence 3", "After sentence 4"],
    "C", "The sentence gives the detail that supports the claim about training in sentence 3."),
  g("WE-44", 2, "organization", "Which sentence best concludes a paragraph arguing that students should learn to cook?",
    ["Cooking classes are offered at many community centers.", "Learning to cook gives students a skill they will use for the rest of their lives.", "My favorite dish is vegetable soup.", "Some ovens are difficult to clean."],
    "B", "B restates the argument's point as a closing statement."),
  g("WE-45", 1, "organization", "Which sentence best opens a paragraph that then lists three reasons to keep a reading journal?",
    ["A reading journal takes only a few minutes a day and pays off in three ways.", "I lost my last notebook.", "Journals can be bought online.", "Some people prefer audiobooks."],
    "A", "A announces the topic and signals that three reasons follow."),
  g("WE-46", 3, "organization", "Which order makes the paragraph most logical?\n\n(1) Finally, press the seams flat. (2) Begin by cutting the fabric to size. (3) Next, pin the two pieces together. (4) Then sew along the marked edge.",
    ["2, 3, 4, 1", "1, 2, 3, 4", "2, 4, 3, 1", "3, 2, 4, 1"],
    "A", "The steps follow cutting, pinning, sewing, and pressing, matching the signal words."),
  g("WE-47", 2, "organization", "Which transition best fits the blank?\n\nThe museum lowered its admission price. ____, attendance rose by a third within two months.",
    ["Nevertheless", "As a result", "On the other hand", "In contrast"],
    "B", "The second sentence gives the outcome of the first."),
  g("WE-48", 2, "organization", "A writer wants to add evidence to a paragraph claiming that school recycling programs work. Which sentence is the best addition?",
    ["Recycling bins are usually blue.", "Since the program began, the school's landfill waste has dropped by 40 percent.", "Many students bring lunch from home.", "The custodians work very hard."],
    "B", "Only B provides measurable evidence supporting the claim."),
  g("WE-49", 3, "organization", "Which sentence should be deleted as repetitive?\n\n(1) The new bell schedule adds five minutes between classes. (2) Students now have more time to reach distant classrooms. (3) The extra five minutes gives students additional time between classes. (4) Teachers report fewer late arrivals.",
    ["Sentence 1", "Sentence 2", "Sentence 3", "Sentence 4"],
    "C", "Sentence 3 repeats information already given in sentences 1 and 2."),
  g("WE-50", 1, "organization", "Which sentence best belongs in the introduction of an essay about local flooding?",
    ["In conclusion, the town must act quickly.", "Each spring, rising water closes the same three roads in our town.", "For example, Maple Street flooded twice in April.", "Finally, drainage repairs would cost money."],
    "B", "The sentence introduces the subject without signaling a conclusion or an example."),
];
