// Paper Folding v2 — 32 original items generated by the fold engine (pool for 15 administered).
// Skills: single_fold (calibration, capped at 2 presented), two_fold_reflection, three_fold_sequence,
// diagonal_reflection, multiple_punches, edge_notch, asymmetric_fold.
import type { BankQuestion } from "./bank-types.ts";
import { buildFoldItem, D, H, V, type FoldItemSpec, type Unfolded } from "./fold-engine.ts";

// Main diagonal of the full sheet (top-left → bottom-right) and the anti-diagonal.
const MAIN_UP = D([0, 0], [100, 100], [100, 0], "the lower-left triangle is folded up over the diagonal from the top-left corner to the bottom-right corner");
const MAIN_DOWN = D([0, 0], [100, 100], [0, 100], "the upper-right triangle is folded down over the diagonal from the top-left corner to the bottom-right corner");
const ANTI_UP = D([100, 0], [0, 100], [0, 0], "the lower-right triangle is folded up over the diagonal from the top-right corner to the bottom-left corner");
// Diagonals of a quarter sheet after two center folds.
const Q_TL = D([0, 0], [50, 50], [50, 0], "the folded quarter sheet is folded along its diagonal from the top-left corner, bringing the lower-left triangle onto the upper-right triangle");
const Q_BR = D([50, 100], [100, 50], [100, 100], "the folded quarter sheet is folded along its diagonal from the bottom-left corner to the top-right corner, bringing the upper-left triangle onto the lower-right triangle");
// Diagonal of a half sheet (after one horizontal fold)
const HALF_D = D([0, 0], [50, 50], [100, 0], "the left corner of the folded strip is folded over along a diagonal from the top-left corner to the middle of the strip's lower edge");

// Correct-answer positions 0..4 (A–E), balanced and non-patterned.
const idx = [0, 2, 4, 1, 3, 3, 0, 4, 2, 1, 1, 4, 3, 0, 2, 2, 3, 1, 4, 0, 4, 2, 0, 3, 1, 1, 0, 4, 2, 3, 3, 4];
const spec = (i: number, s: Omit<FoldItemSpec, "correctIndex">): FoldItemSpec => ({ ...s, correctIndex: idx[i] });

export const PAPER_FOLDING_V2_SPECS: FoldItemSpec[] = [
  // ----- single_fold (4, L1 calibration) -----
  spec(0, { code: "PF2-01", difficulty: 1, skill: "single_fold", folds: [V(50, "left")], holes: [[25, 30]] }),
  spec(1, { code: "PF2-02", difficulty: 1, skill: "single_fold", folds: [H(50, "top")], holes: [[70, 20]] }),
  spec(2, { code: "PF2-03", difficulty: 1, skill: "single_fold", folds: [V(50, "right")], holes: [[80, 65]] }),
  spec(3, { code: "PF2-04", difficulty: 1, skill: "single_fold", folds: [H(50, "bottom")], holes: [[30, 85]] }),
  // ----- two_fold_reflection (6) -----
  spec(4, { code: "PF2-05", difficulty: 2, skill: "two_fold_reflection", folds: [V(50, "left"), H(50, "top")], holes: [[20, 20]] }),
  spec(5, { code: "PF2-06", difficulty: 2, skill: "two_fold_reflection", folds: [H(50, "bottom"), V(50, "right")], holes: [[70, 80]] }),
  spec(6, { code: "PF2-07", difficulty: 2, skill: "two_fold_reflection", folds: [V(50, "right"), H(50, "bottom")], holes: [[85, 60]] }),
  spec(7, { code: "PF2-08", difficulty: 2, skill: "two_fold_reflection", folds: [V(50, "left"), H(50, "top")], holes: [[44, 10]] }),
  spec(8, { code: "PF2-09", difficulty: 3, skill: "two_fold_reflection", folds: [V(50, "left"), V(25, "left")], holes: [[12, 40]] }),
  spec(9, { code: "PF2-10", difficulty: 3, skill: "two_fold_reflection", folds: [H(50, "top"), H(25, "top")], holes: [[60, 8]] }),
  // ----- three_fold_sequence (6) -----
  spec(10, { code: "PF2-11", difficulty: 2, skill: "three_fold_sequence", folds: [V(50, "left"), H(50, "top"), V(25, "left")], holes: [[12, 20]] }),
  spec(11, { code: "PF2-12", difficulty: 2, skill: "three_fold_sequence", folds: [H(50, "top"), V(50, "left"), H(25, "top")], holes: [[30, 12]] }),
  spec(12, { code: "PF2-13", difficulty: 3, skill: "three_fold_sequence", folds: [V(50, "left"), H(50, "top"), Q_TL], holes: [[35, 15]] }),
  spec(13, { code: "PF2-14", difficulty: 3, skill: "three_fold_sequence", folds: [V(50, "right"), H(50, "bottom"), Q_BR], holes: [[85, 85]] }),
  spec(14, { code: "PF2-15", difficulty: 3, skill: "three_fold_sequence", folds: [H(50, "bottom"), V(50, "right"), H(75, "bottom")], holes: [[80, 90]] }),
  spec(15, { code: "PF2-16", difficulty: 3, skill: "three_fold_sequence", folds: [V(50, "left"), H(50, "top"), V(25, "left")], holes: [[8, 42], [17, 14]] }),
  // ----- diagonal_reflection (5) -----
  spec(16, { code: "PF2-17", difficulty: 2, skill: "diagonal_reflection", folds: [MAIN_UP], holes: [[70, 30]] }),
  spec(17, { code: "PF2-18", difficulty: 2, skill: "diagonal_reflection", folds: [ANTI_UP], holes: [[25, 40]] }),
  spec(18, { code: "PF2-19", difficulty: 2, skill: "diagonal_reflection", folds: [MAIN_DOWN], holes: [[30, 75]] }),
  spec(19, { code: "PF2-20", difficulty: 3, skill: "diagonal_reflection", folds: [MAIN_UP, V(50, "right")], holes: [[70, 20]] }),
  spec(20, { code: "PF2-21", difficulty: 3, skill: "diagonal_reflection", folds: [H(50, "top"), HALF_D], holes: [[20, 10], [75, 30]] }),
  // ----- multiple_punches (4) -----
  spec(21, { code: "PF2-22", difficulty: 2, skill: "multiple_punches", folds: [V(50, "left")], holes: [[15, 20], [35, 70]] }),
  spec(22, { code: "PF2-23", difficulty: 2, skill: "multiple_punches", folds: [H(50, "bottom")], holes: [[25, 80], [60, 60]] }),
  spec(23, { code: "PF2-24", difficulty: 3, skill: "multiple_punches", folds: [V(50, "left"), H(50, "top")], holes: [[10, 10], [40, 40]] }),
  spec(24, { code: "PF2-25", difficulty: 3, skill: "multiple_punches", folds: [H(50, "top"), V(50, "right")], holes: [[60, 15], [90, 40], [75, 30]] }),
  // ----- edge_notch (3) -----
  spec(25, { code: "PF2-26", difficulty: 2, skill: "edge_notch", folds: [V(50, "left")], holes: [[30, 60]], cuts: [[[15, 0], [25, 0], [20, 8]]] }),
  spec(26, { code: "PF2-27", difficulty: 2, skill: "edge_notch", folds: [V(50, "left"), H(50, "top")], holes: [[35, 15]], cuts: [[[0, 25], [0, 35], [8, 30]]] }),
  spec(27, { code: "PF2-28", difficulty: 3, skill: "edge_notch", folds: [H(50, "bottom"), V(50, "right")], holes: [[60, 85]], cuts: [[[65, 100], [75, 100], [70, 92]]] }),
  // ----- asymmetric_fold (4) -----
  spec(28, { code: "PF2-29", difficulty: 2, skill: "asymmetric_fold", folds: [V(30, "right")], holes: [[40, 50]] }),
  spec(29, { code: "PF2-30", difficulty: 2, skill: "asymmetric_fold", folds: [H(70, "top")], holes: [[50, 62]] }),
  spec(30, { code: "PF2-31", difficulty: 3, skill: "asymmetric_fold", folds: [V(30, "right"), H(50, "top")], holes: [[40, 20], [80, 35]] }),
  spec(31, { code: "PF2-32", difficulty: 3, skill: "asymmetric_fold", folds: [H(50, "top"), V(75, "left")], holes: [[60, 30], [15, 10]] }),
];

const built = PAPER_FOLDING_V2_SPECS.map(buildFoldItem);

/** Model outputs kept alongside the bank for automated QA (not seeded to the database). */
export const PAPER_FOLDING_V2_MODELS: Record<string, { correct: Unfolded; distractors: { label: string; u: Unfolded }[] }> =
  Object.fromEntries(built.map((b) => [b.code, b.model]));

export const PAPER_FOLDING_V2: BankQuestion[] = built.map(({ model: _m, ...q }) => q);
